language: generic
sudo: required
dist: trusty

env:
  - SWIFT_VERSION=4.0
  - SWIFT_VERSION=3.0
  - SWIFT_VERSION=3.1.1

install:
  - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
script:
  - swift build
  - swift test
